#!/usr/bin/env bash
# 测试 runner：模拟 workbuddy CLI 成功生成 HTML
# 验证后端 spawn 链路 + 上传逻辑
set -e

sleep 1
cat > "${OUTPUT_FILE_FOR_RUN}" <<EOF
<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="utf-8"><title>Test ${DATE_FOR_RUN}</title></head>
<body>
<h1>Test runner run#${RUN_ID_FOR_RUN} date=${DATE_FOR_RUN}</h1>
<p>PROMPT bytes: ${#PROMPT}</p>
<p>HOLDINGS bytes: ${#HOLDINGS}</p>
<p>Generated by test-runner.sh at $(date)</p>
</body>
</html>
EOF
exit 0
